/**
 * Event archive import.
 *
 * E:/SIR NEWSON WORLD/EVENTS holds print-resolution PNGs organised the way the
 * work actually happened — series / edition / assets. That structure is the
 * whole point of the events page, so unlike import-assets.mjs this one keeps it
 * instead of flattening everything into one client folder.
 *
 * Resizes to web scale and writes WebP into public/uploads/events-archive,
 * then generates src/data/eventGallery.ts.
 *
 *   node scripts/import-events.mjs
 */
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const SRC_ROOT = 'E:/SIR NEWSON WORLD/EVENTS';
const OUT_ROOT = 'public/uploads/events-archive';
const DATA_OUT = 'src/data/eventGallery.ts';
const MAX_W = 1200;
const QUALITY = 76;

/** Source folder -> the series key used in src/data/events.ts. */
const SERIES = {
    'mapenzi vibandaski': 'mapenzi-vibandaski',
    'Kwa Ndego': 'kwa-ndego',
    'big voice fest': 'big-voice-fest',
    ttnt: 'ttnt',
};

const IMG = /\.(png|jpe?g|webp)$/i;

const slug = (s) =>
    s
        .replace(/\.[^.]+$/, '')
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[^\w\s-]/g, '')
        .trim()
        .replace(/[\s_]+/g, '-')
        .replace(/-+/g, '-')
        .slice(0, 60) || 'asset';

const title = (s) =>
    slug(s)
        .split('-')
        .filter(Boolean)
        .map((w) => (w.length <= 2 ? w.toUpperCase() : w[0].toUpperCase() + w.slice(1)))
        .join(' ');

/**
 * Filenames here are working names, so the first asset in a folder is arbitrary.
 * Nudge the ones that read like a main poster to the front, because the first
 * item becomes the edition's cover on the site.
 */
const HERO = /(final|main|poster|full|bill|artwall|billboard)/i;
const heroRank = (name) => (HERO.test(name) ? 0 : 1);

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const rows = [];

for (const [folder, seriesKey] of Object.entries(SERIES)) {
    const seriesDir = path.join(SRC_ROOT, folder);
    let editions;
    try {
        editions = await readdir(seriesDir, { withFileTypes: true });
    } catch {
        console.warn(`skip ${folder} — not readable`);
        continue;
    }

    for (const ed of editions) {
        if (!ed.isDirectory()) continue;
        const editionKey = slug(ed.name);
        const editionDir = path.join(seriesDir, ed.name);

        const files = (await readdir(editionDir, { withFileTypes: true }))
            .filter((f) => f.isFile() && IMG.test(f.name))
            .map((f) => f.name)
            .sort((a, b) => heroRank(a) - heroRank(b) || a.localeCompare(b));

        if (files.length === 0) {
            console.log(`  ${seriesKey}/${editionKey}: empty`);
            continue;
        }

        const outDir = path.join(OUT_ROOT, seriesKey, editionKey);
        await mkdir(outDir, { recursive: true });

        for (const name of files) {
            const base = slug(name);
            const out = path.join(outDir, `${base}.webp`);
            const meta = await sharp(path.join(editionDir, name))
                .resize({ width: MAX_W, withoutEnlargement: true })
                .webp({ quality: QUALITY })
                .toFile(out);

            rows.push({
                id: `${seriesKey}-${editionKey}-${base}`,
                seriesKey,
                editionKey,
                title: title(name),
                src: `/${path.posix.join(OUT_ROOT.replace(/^public\//, ''), seriesKey, editionKey, `${base}.webp`)}`,
                w: meta.width,
                h: meta.height,
            });
        }
        console.log(`  ${seriesKey}/${editionKey}: ${files.length}`);
    }
}

const body = rows
    .map(
        (r) =>
            `    { id: '${esc(r.id)}', seriesKey: '${esc(r.seriesKey)}', editionKey: '${esc(
                r.editionKey
            )}', title: '${esc(r.title)}', src: '${esc(r.src)}', w: ${r.w}, h: ${r.h} },`
    )
    .join('\n');

const file = `/**
 * Generated by scripts/import-events.mjs — do not edit by hand.
 * Source PNGs live in E:/SIR NEWSON WORLD/EVENTS and were resized to ${MAX_W}px
 * and re-encoded to WebP on import, so nothing here is print-resolution.
 */

export interface EventAsset {
    id: string;
    /** Matches EventSeries.key in ./events. */
    seriesKey: string;
    /** Matches EventEdition.assetKey in ./events. */
    editionKey: string;
    title: string;
    src: string;
    w: number;
    h: number;
}

export const eventAssets: EventAsset[] = [
${body}
];

export const assetsForEdition = (seriesKey: string, editionKey?: string) =>
    editionKey
        ? eventAssets.filter((a) => a.seriesKey === seriesKey && a.editionKey === editionKey)
        : [];

export const assetsForSeries = (seriesKey: string) =>
    eventAssets.filter((a) => a.seriesKey === seriesKey);
`;

await writeFile(DATA_OUT, file, 'utf8');
console.log(`\n${rows.length} assets -> ${DATA_OUT}`);
