import { byClient, type PortfolioItem } from './portfolio';
import { assetsForEdition, assetsForSeries, type EventAsset } from './eventGallery';

/* ---------------------------------------------------------------
   The event docket, as a run of series rather than a pile of posters.

   Almost everything here is recurring work: the same night, the same
   festival, the same tour, coming back with a new number on it. That
   repeat is the actual story — a poster is one job, a fourth season is a
   relationship — so the page is built around series and their editions,
   and the artwork hangs off that spine.

   Two archives feed it. `assetKey` reaches the per-edition import in
   ./eventGallery (generated by scripts/import-events.mjs); `clientKey`
   reaches the older flat client import in ./portfolio, which has no
   edition breakdown.

   Dates, venues and line-ups are deliberately absent. They are not
   recorded anywhere in this repo, and inventing them would put false
   claims on a public page. Add them to `editions[].note` as they get
   confirmed.
   --------------------------------------------------------------- */

export interface EventEdition {
    /** The run marker — "SN 4", "Edition II". */
    label: string;
    /** The edition's own name, where it has one. */
    name?: string;
    /** Anything confirmed and worth showing: a year, a venue, a headline. */
    note?: string;
    /** Folder key in the per-edition archive. Absent = nothing imported yet. */
    assetKey?: string;
}

export interface EventSeries {
    key: string;
    name: string;
    /** What kind of night it is. */
    kind: string;
    blurb: string;
    /** Oldest first. The page numbers them and marks the last as latest. */
    editions: EventEdition[];
    /** Links the series to the older flat archive, which has no editions. */
    clientKey?: string;
    /** Overrides the cover. Otherwise the first imported asset is used. */
    poster?: string;
}

export const eventSeries: EventSeries[] = [
    {
        key: 'mapenzi-vibandaski',
        name: 'Mapenzi Vibandaski',
        kind: 'Live Music & Culture',
        blurb: 'Four seasons of the same idea, each one asked to feel bigger than the last without losing what made the first one work.',
        editions: [
            { label: 'SN 1', assetKey: 'sn-1' },
            { label: 'SN 2', assetKey: 'sn-2' },
            { label: 'SN 3', assetKey: 'sn-3' },
            { label: 'SN 4', assetKey: 'sn4' },
        ],
    },
    {
        key: 'ttnt',
        name: 'TTNT',
        kind: 'Live Comedy Tour',
        blurb: 'A touring comedy franchise that arrives with an audience already waiting — so the campaign works on anticipation rather than explanation.',
        editions: [
            { label: 'TTNT 4', assetKey: 'ttnt-4' },
            { label: 'TTNT 5', assetKey: 'ttnt-5' },
            {
                label: 'TTNT 6',
                note: 'Full campaign — programme, bills, socials, wallpapers',
                assetKey: 'ttnt-6',
            },
        ],
    },
    {
        key: 'big-voice-fest',
        name: 'Big Voice Fest',
        kind: 'Music Festival',
        blurb: 'A festival that renames itself every season. Each edition needs its own identity while still reading as the same festival on the third look.',
        editions: [
            { label: 'SN 1' },
            { label: 'SN 2', name: 'Millennial Edition', assetKey: 'millenial' },
            { label: 'SN 3', name: 'Mahaba Edition', assetKey: 'mahaba' },
        ],
    },
    {
        key: 'the-juice-party',
        name: 'The Juice Party',
        kind: 'Nightlife',
        blurb: 'A party that grew out of its own numbering — by the third outing it needed a name rather than an edition number.',
        editions: [{ label: '2nd Edition' }, { label: 'The Trinity Experience' }],
    },
    {
        key: 'kwa-ndego',
        name: 'Kwa Ndego',
        kind: 'Culture & Heritage Nights',
        blurb: 'A creative hub running themed nights named after the stories they sit inside. The design job is to make heritage feel current without costuming it.',
        editions: [
            { label: 'Edition I', name: 'Wangu wa Makeri', assetKey: 'wangu-wa-makeri' },
            { label: 'Edition II', name: 'Gikuyu na Mumbi', assetKey: 'gikuyu-na-mumbi' },
            { label: 'Edition III', name: 'Matigari ma Njirungi', assetKey: 'matigari-ma-njirungi' },
            { label: 'Edition IV', name: 'Hutia Kirima', assetKey: 'hutia-kirima' },
        ],
    },
    {
        key: 'last-call',
        name: 'Last Call',
        kind: 'Events & Nightlife',
        blurb: 'Nightlife rollout at speed — themes, locations and ticket pushes that have to land the same week they are decided.',
        editions: [{ label: 'Rucio' }],
        clientKey: 'lastcall',
    },
    {
        key: 'matatu',
        name: 'Matatu',
        kind: 'Culture & Events',
        blurb: 'Stage and culture work — bills, backdrops and the re-run campaign that sold the second sitting.',
        editions: [{ label: 'Re-run' }],
        clientKey: 'matatu',
    },
];

/* ---------------------------------------------------------------
   Work built alongside the campaigns rather than inside one. Copy is
   taken from the live product, not written from the name.
   --------------------------------------------------------------- */

export interface PartnerProject {
    name: string;
    domain: string;
    href: string;
    /** Who it was built with. */
    partner: { name: string; href: string };
    tagline: string;
    blurb: string;
    includes: string[];
    /** Events on the platform that also appear in the docket above. */
    seenOn?: { label: string; seriesKey?: string }[];
}

export const partnerProjects: PartnerProject[] = [
    {
        name: 'Invait',
        domain: 'invait.co.ke',
        href: 'https://invait.co.ke',
        partner: { name: 'YXM Digital', href: 'https://yxmdigital.com/' },
        tagline: 'Digital invitations that open like a letter.',
        blurb: 'Every invite lives on its own private address, shared only with that event’s guest list — built around the event’s own branding rather than a template, and designed for the phone first.',
        includes: [
            'Its own web address, hosted',
            'Custom animated opening',
            'Live countdown and add-to-calendar',
            'Maps, directions, RSVP and ticket links',
            'WhatsApp share preview with your artwork',
        ],
        seenOn: [
            { label: 'Big Voice Fest — Mahaba Edition', seriesKey: 'big-voice-fest' },
            { label: 'Becoming CEO LIVE' },
        ],
    },
];

/** The per-edition archive for one edition. */
export const editionArtwork = (series: EventSeries, edition: EventEdition): EventAsset[] =>
    assetsForEdition(series.key, edition.assetKey);

/** The older flat archive, for series imported before editions were tracked. */
export const seriesArtwork = (series: EventSeries): PortfolioItem[] =>
    series.clientKey ? byClient(series.clientKey) : [];

/** The cover a series leads with: an override, else its first imported asset. */
export const seriesCover = (series: EventSeries): string | undefined =>
    series.poster ?? assetsForSeries(series.key)[0]?.src ?? seriesArtwork(series)[0]?.src;

/** How many editions actually have artwork on file. */
export const editionsWithArtwork = (series: EventSeries) =>
    series.editions.filter((e) => editionArtwork(series, e).length > 0).length;

export const totalEditions = eventSeries.reduce((n, s) => n + s.editions.length, 0);
